### ISSUE TITLE
Research data: collection

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/ai_genomics#2]
Assess OpenAlex. Some questions to consider:
  * What is its coverage?
  * What is its timeliness?
  * How will we collect it?
  * How will we store it?
  * How will we find AI / genomics papers in it?

**Comment by Jack-Vines** [comment]
Some discussion of OpenAlex quality here: https://bibliometrie.info/downloads/webinarslides/2022_03_25_Open_Data_Open_Science.pdf
