### ISSUE TITLE
There are some patents with titles in languages other than english

### ISSUE THREAD

**Issue by Jack-0-0** [nestauk/ai_genomics#75]
e.g 
3270,EP-3622524-A1,Variantenklassierer auf der basis von tiefen neuronalen netzen
2868,KR-20160057792-A,SiNG-PCRseq 방법을 적용한 핵산의 표준화 정량 분석 방법
8397,RU-2746477-C2,Способы и системы для определения вариантов числа копий,"FIELD: biotechnology.

**Comment by india-kerle** [comment]
UPDATE: instead of just dropping rows with non-english titles, just do some analysis on whether we're dropping english titles when we query in bigquery

**Comment by india-kerle** [comment]
turns out this was a bit buggy - modified query to make sure we're not dropping english titles when we query in bigquery in branch 81_patent_topics.
