### ISSUE TITLE
Patents: Sources

### ISSUE THREAD

**Issue by Juan-Mateos** [nestauk/ai_genomics#8]
Some options:
* Patent lens
* Global Patent Index
* USPTO using the open AI patent dataset (https://www.uspto.gov/ip-policy/economic-research/research-datasets/artificial-intelligence-patent-dataset)
* Google Patent dataset @Big query
* Check with Karlis / Discovery Hub about their plans to analyse patent data

**Comment by india-kerle** [comment]
happy to take on this issue although @Juan-Mateos I cannot assign issues to myself as I think you need to give me/probably the rest of the team the right permissions to.

**Comment by india-kerle** [comment]
- speak with Karlis about how much work discovery hub has done here to see how much more we need to do here.
